///////////////////////////////////////////////////////////
//  BotDrive.cs
//  Implementation of the Class BotDrive
//  Generated by Enterprise Architect
//  Created on:      23-十二月-2018 下午 06:24:27
//  Original author: satan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class BotDrive : MonoBehaviour {

	private Simulation ann;
	public int epochs = 1000;
	private double lastSSE = 1;
	public bool loadFromFile = false;
	public float rotation;
	public float rotationSpeed = 100.0F;
	public float speed = 50.0F;
	private double sse = 0;
	private bool trainingDone = false;
	private float trainingProgress = 0;
	public float translation;
	public float visibleDistance = 200;

	public BotDrive(){

	}

	~BotDrive(){

	}

	private IEnumerator LoadTrainingSet(){

		return null;
	}

	private void LoadWeightsFromFile(){

	}

	/// 
	/// <param name="newfrom"></param>
	/// <param name="newto"></param>
	/// <param name="origfrom"></param>
	/// <param name="origto"></param>
	/// <param name="value"></param>
	private float Map(float newfrom, float newto, float origfrom, float origto, float value){

		return 0;
	}

	private void OnGUI(){

	}

	/// 
	/// <param name="x"></param>
	private float Round(float x){

		return 0;
	}

	private void SaveWeightsToFile(){

	}

	/// <summary>
	/// Use this for initialization
	/// </summary>
	private void Start(){

	}

	private void Update(){

	}

}//end BotDrive