///////////////////////////////////////////////////////////
//  Simulation.cs
//  Implementation of the Class Simulation
//  Generated by Enterprise Architect
//  Created on:      23-十二月-2018 下午 06:24:27
//  Original author: satan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Simulation {

	public double alpha;
	private List<Layer> layers = new List<Layer>();
	public int numHidden;
	public int numInputs;
	public int numNPerHidden;
	public int numOutputs;

	public Simulation(){

	}

	~Simulation(){

	}

	/// 
	/// <param name="nI"></param>
	/// <param name="nO"></param>
	/// <param name="nH"></param>
	/// <param name="nPH"></param>
	/// <param name="a"></param>
	public Simulation(int nI, int nO, int nH, int nPH, double a){

	}

	/// 
	/// <param name="value"></param>
	private double ActivationFunction(double value){

		return 0;
	}

	/// 
	/// <param name="value"></param>
	private double ActivationFunctionO(double value){

		return 0;
	}

	/// 
	/// <param name="inputValues"></param>
	/// <param name="desiredOutput"></param>
	public List<double> CalcOutput(List<double> inputValues, List<double> desiredOutput){

		return null;
	}

	/// 
	/// <param name="value"></param>
	private double LeakyReLu(double value){

		return 0;
	}

	/// 
	/// <param name="weightStr"></param>
	public void LoadWeights(string weightStr){

	}

	public string PrintWeights(){

		return "";
	}

	/// 
	/// <param name="value"></param>
	private double ReLu(double value){

		return 0;
	}

	/// 
	/// <param name="value"></param>
	private double Sigmoid(double value){

		return 0;
	}

	/// 
	/// <param name="value"></param>
	private double TanH(double value){

		return 0;
	}

	/// 
	/// <param name="inputValues"></param>
	/// <param name="desiredOutput"></param>
	public List<double> Train(List<double> inputValues, List<double> desiredOutput){

		return null;
	}

	/// 
	/// <param name="outputs"></param>
	/// <param name="desiredOutput"></param>
	private void UpdateWeights(List<double> outputs, List<double> desiredOutput){

	}

}//end Simulation